# Generated by Django 6.0.6 on 2026-07-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_terminal_module_user_management'),
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='Optional terminal assigned to this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='companies.terminal', verbose_name='Terminal'),
        ),
    ]