# Stage 1: Build
FROM node:20-slim AS builder

WORKDIR /app

# Dependencies install
COPY package*.json .
RUN npm install --legacy-peer-deps
RUN npm install terser --legacy-peer-deps
RUN npm install vite@5.4.0 --legacy-peer-deps
# Code copy aur build
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Vue build files copy karo
COPY --from=builder /app/dist /usr/share/nginx/html

# Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]