# Generated by Django 6.0.6 on 2026-07-03 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_warehouse'),
        ('pos', '0014_alter_salepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity in Stock')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, help_text='Alert when quantity falls below this. Set 0 to disable.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Low Stock Threshold')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='pos.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='companies.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Stock',
                'verbose_name_plural': 'Warehouse Stock',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
