# Generated by Django 6.0.6 on 2026-07-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_alter_salereturnline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate_percent',
            field=models.CharField(choices=[('0%', '0% — Zero Rated'), ('Exempt', 'Exempt (Statutory)'), ('1%', '1%'), ('2%', '2%'), ('3%', '3%'), ('5%', '5% — Reduced Rate'), ('10%', '10%'), ('12%', '12%'), ('13%', '13%'), ('15%', '15%'), ('17%', '17%'), ('18%', '18% — Standard Rate'), ('20%', '20%'), ('25%', '25%')], default='18%', help_text="Sales tax rate. Maps to 'rate' in FBR invoice JSON. Use 0% for exempt or zero-rated goods.", max_length=10, verbose_name='Tax Rate'),
        ),
    ]
