# Generated by Django 6.0.6 on 2026-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_alter_product_tax_rate_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vendor_code',
            field=models.CharField(blank=True, default='0', help_text='Optional code assigned to the customer.', max_length=50, null=True, verbose_name='Vendor Code'),
        ),
    ]
