# Generated by Django 6.0.6 on 2026-07-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_customer_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vendor_code',
            field=models.CharField(blank=True, default='', help_text='Optional vendor code for this invoice. Can be different for each invoice.', max_length=50, null=True, verbose_name='Vendor Code'),
        ),
    ]
