# Generated by Django 6.0.6 on 2026-07-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_migrate_vendor_code_to_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vendor_code',
        ),
    ]
