# Generated by Django 6.0.6 on 2026-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_remove_customer_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pct_code',
            field=models.CharField(blank=True, help_text="8-digit Product Classification Tax code for FBR Retail POS integration. Required for POS clients. Maps to 'PCTCode' in POS invoice JSON.", max_length=8, verbose_name='PCT Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text="Harmonized System code. REQUIRED by FBR for manufacturer-cum-retailer. Format: XXXX.XXXX (e.g. 0101.2100). Maps to 'hsCode' in FBR DI invoice JSON.", max_length=20, verbose_name='HS Code'),
        ),
    ]
