# Generated by Django 6.0.6 on 2026-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_product_pct_code_alter_product_hs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text="Harmonized System code. REQUIRED by FBR for manufacturer-cum-retailer. Format: XXXX.XXXX (e.g. 2106.9090). Maps to 'hsCode' in FBR DI invoice JSON. Auto-syncs with PCT Code for POS clients.", max_length=20, verbose_name='HS Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pct_code',
            field=models.CharField(blank=True, help_text="8-digit Product Classification Tax code for FBR Retail POS integration. Required for POS clients. Maps to 'PCTCode' in POS invoice JSON. Auto-syncs with HS Code (enter either one, the other is auto-generated).", max_length=8, verbose_name='PCT Code'),
        ),
    ]
