# Generated by Django 6.0.6 on 2026-08-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_alter_product_hs_code_alter_product_pct_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_challan_number',
            field=models.CharField(blank=True, help_text='Optional Delivery Challan / Reference Number for this sale/invoice.', max_length=100, null=True, verbose_name='Delivery Challan Number'),
        ),
    ]
