# Generated by Django 6.0.6 on 2026-07-18 07:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0010_alter_company_logo'),
        ('pos', '0021_alter_product_tax_rate_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('permotted', 'Permotted'), ('repeated', 'Repeated'), ('left', 'Left')], default='active', max_length=20)),
                ('student_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.academicsession')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.academicsession')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubjectSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33, max_digits=6)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_schedules', to='school.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='"Mid Term", "Final Term", "Monthly Test"', max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.examtype'),
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('default_pct_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_heads', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partial')], default='unpaid', max_length=20)),
                ('total_concession_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_status_fbr', models.CharField(choices=[('draft', 'Draft'), ('sent_to_fbr', 'Sent to FBR'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('fbr_invoice_number', models.CharField(blank=True, help_text='Mirrors what core Invoice already stores, denormalized for fast school-side lookup', max_length=100, null=True)),
                ('generated_by', models.CharField(choices=[('auto', 'Auto (batch job)'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('academic_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='school.academicsession')),
                ('core_invoice_id', models.ForeignKey(blank=True, help_text='Link to the core POS Sale for FBR submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='pos.sale')),
                ('enrollement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='school.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='FeeInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, help_text='Denormalized snapshot of fee head name at time of billing', max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pct_code', models.CharField(blank=True, help_text='Snapshot of FBR PCT code used', max_length=20, null=True)),
                ('fee_head_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='school.feehead')),
                ('fee_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school.feeinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.academicsession')),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='fee_structure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='school.feestructure'),
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('fee_head_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='school.feehead')),
                ('fee_structure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='school.feestructure')),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='feestructure',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.grade'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='school.grade'),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.grade'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.grade'),
        ),
        migrations.CreateModel(
            name='guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='guardian_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='school.guardian'),
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('academic_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.academicsession')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.grade')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.section'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='class_teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='school.staff'),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('online', 'Online'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='e.g. cheque number', max_length=100, null=True)),
                ('fee_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.feeinvoice')),
                ('received_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='school.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('current_section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.section')),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='school.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.student'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('enrollement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='school.staff')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade_letter', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.enrollment')),
                ('exam_subject_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='school.examsubjectschedule')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeConcession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consession_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='fixed', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fee_concessions', to='school.staff')),
                ('enrollement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_concessions', to='school.enrollment')),
                ('fee_head_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_concessions', to='school.feehead')),
                ('fee_structure_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_concessions', to='school.feestructureitem')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_concessions', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardianAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary_billing_contact', models.BooleanField(default=False)),
                ('guardian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='school.guardian')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_assignments', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('tennant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='examsubjectschedule',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='school.subject'),
        ),
        migrations.CreateModel(
            name='ClassSubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_assignments', to='school.section')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subject_assignments', to='school.staff')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_assignments', to='school.subject')),
            ],
        ),
    ]
