# Generated by Django 6.0.6 on 2026-08-05 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Category',
                'verbose_name_plural': 'Help Categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=512, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=20, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='docs.helpcategory')),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
