# Generated by Django 6.0.6 on 2026-07-04

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='module_user_management',
            field=models.BooleanField(default=False, help_text='Owner-side user creation, role assignment, and permissions.', verbose_name='User Management'),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Terminal Name')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='Device Fingerprint')),
                ('terminal_index', models.CharField(blank=True, max_length=50, verbose_name='Terminal Index')),
                ('pairing_code', models.CharField(blank=True, max_length=32, verbose_name='Pairing Code')),
                ('pairing_code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Pairing Code Expires At')),
                ('paired_at', models.DateTimeField(blank=True, null=True, verbose_name='Paired At')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='OS Version')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='App Version')),
                ('printer_config', models.JSONField(blank=True, default=dict, verbose_name='Printer Config')),
                ('scanner_config', models.JSONField(blank=True, default=dict, verbose_name='Scanner Config')),
                ('drawer_config', models.JSONField(blank=True, default=dict, verbose_name='Drawer Config')),
                ('customer_display_enabled', models.BooleanField(default=False, verbose_name='Customer Display Enabled')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen At')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='companies.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'branch'], name='terminal_company_branch_idx'), models.Index(fields=['company', 'is_active'], name='terminal_company_active_idx')],
            },
        ),
    ]