# Generated by Django 6.0.6 on 2026-07-09 14:38

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_terminal_module_user_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.CompanyLogoStorage(), upload_to=config.storage_backends.company_logo_upload_path, verbose_name='Company Logo'),
        ),
    ]
