# Generated by Django 6.0.6 on 2026-07-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pos_access_code',
            field=models.CharField(blank=True, help_text='Access Code for POS integration. Entered by the client in FBR settings page.', max_length=100, verbose_name='POS Access Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_id',
            field=models.CharField(blank=True, help_text='POS Registration Number issued by FBR after POS Client Registration. Entered by the client in FBR settings page.', max_length=20, verbose_name='POS ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_production_endpoint',
            field=models.URLField(blank=True, default='https://gw.fbr.gov.pk/imsp/v1/api/Live/PostData', help_text='FBR POS Production API endpoint.', verbose_name='POS Production Endpoint'),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_production_token',
            field=models.TextField(blank=True, help_text='Production token for live POS invoice submission. Entered by the client in FBR settings page.', verbose_name='POS Production Token'),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_sandbox_endpoint',
            field=models.URLField(blank=True, default='https://esp.fbr.gov.pk:8244/FBR/v1/api/Live/PostData', help_text='FBR POS Sandbox API endpoint.', verbose_name='POS Sandbox Endpoint'),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_sandbox_token',
            field=models.TextField(blank=True, help_text='Sandbox token for POS testing. Entered by the client in FBR settings page.', verbose_name='POS Sandbox Token'),
        ),
    ]
