# Generated by Django 6.0.6 on 2026-07-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vertical',
            field=models.CharField(choices=[('grocery', 'Grocery Store'), ('general_store', 'General Store'), ('restaurant', 'Restaurant / F&B'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('clothing', 'Clothing / Apparel'), ('wholesale', 'Wholesale'), ('school', 'School / Education'), ('other', 'Other')], default='general_store', help_text='Controls which POS features/UI this company sees. Independent of FBR Sector.', max_length=30, verbose_name='Business Vertical'),
        ),
    ]
