# Generated by Django 6.0.6 on 2026-08-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_vertical'),
        ('companies', '0011_company_pos_access_code_company_pos_id_and_more'),
    ]

    operations = [
    ]
